export const bankcode = [
    { code: 'NCB', name: 'Ngân hàng Quốc dân (NCB)'},
    { code: 'ABBANK', name: 'Ngân hàng thương mại cổ phần An Bình (ABBANK)'},
    { code: 'ACB', name: 'Ngân hàng ACB'},
    { code: 'AGRIBANK', name: 'Ngân hàng Nông nghiệp (Agribank)'},
    { code: 'BACABANK', name: 'Ngân Hàng TMCP Bắc Á'},
    { code: 'BIDV', name: 'Ngân hàng đầu tư và phát triển Việt Nam (BIDV)'},
    { code: 'DONGABANK', name: 'Ngân hàng Đông Á (DongABank)'},
    { code: 'EXIMBANK', name: 'Ngân hàng EximBank'},
    { code: 'HDBANK', name: 'Ngân hàng HDBank'},
    { code: 'IVB', name: 'Ngân hàng TNHH Indovina (IVB)'},
    { code: 'MBBANK', name: 'Ngân hàng thương mại cổ phần Quân đội'},
    { code: 'MSBANK', name: 'Ngân hàng Hàng Hải (MSBANK)'},
    { code: 'NAMABANK', name: 'Ngân hàng Nam Á (NamABank)'},
    { code: 'OCB', name: 'Ngân hàng Phương Đông (OCB)'},
    { code: 'OJB', name: 'Ngân hàng Đại Dương (OceanBank)'},
    { code: 'PVCOMBANK', name: 'Ngân hàng TMCP Đại Chúng Việt Nam'},
    { code: 'SACOMBANK', name: 'Ngân hàng TMCP Sài Gòn Thương Tín (SacomBank)'},
    { code: 'SAIGONBANK', name: 'Ngân hàng thương mại cổ phần Sài Gòn Công Thương'},
    { code: 'SCB', name: 'Ngân hàng TMCP Sài Gòn (SCB)'},
    { code: 'SHB', name: 'Ngân hàng Thương mại cổ phần Sài Gòn - Hà Nội(SHB)'},
    { code: 'TECHCOMBANK', name: 'Ngân hàng Kỹ thương Việt Nam (TechcomBank)'},
    { code: 'TPBANK', name: 'Ngân hàng Tiên Phong (TPBank)'},
    { code: 'VPBANK', name: 'Ngân hàng Việt Nam Thịnh vượng (VPBank)'},
    { code: 'SEABANK', name: 'Ngân Hàng TMCP Đông Nam Á'},
    { code: 'VIB', name: 'Ngân hàng Thương mại cổ phần Quốc tế Việt Nam (VIB)'},
    { code: 'VIETABANK', name: '	Ngân hàng TMCP Việt Á'},
    { code: 'VIETBANK', name: 'Ngân hàng thương mại cổ phần Việt Nam Thương Tín'},
    { code: 'VIETCAPITALBANK', name: 'Ngân Hàng Bản Việt'},
    { code: 'VIETCOMBANK', name: 'Ngân hàng Ngoại thương (Vietcombank)'},
    { code: 'VIETINBANK', name: 'Ngân hàng Công thương (Vietinbank)'},
    // { code: '', name: ''},
    // { code: '', name: ''},
    // { code: '', name: ''},
    // { code: '', name: ''},
    // { code: '', name: ''},
    // { code: '', name: ''},
    // { code: '', name: ''},
    // { code: '', name: ''},
    // { code: '', name: ''},
    // { code: '', name: ''},
    // { code: '', name: ''},
    // { code: '', name: ''},
    // { code: '', name: ''},
    // { code: '', name: ''},
    // { code: '', name: ''},
    // { code: '', name: ''},
    // { code: '', name: ''},
    // { code: '', name: ''},
    // { code: '', name: ''},
    // { code: '', name: ''},
    // { code: '', name: ''},
    // { code: '', name: ''},


]